name: Mantener Streamlit Activo

on:
  schedule:
       - cron: '0 */6 * * *' # Se ejecuta automáticamente cada 6 horas
  workflow_dispatch: # Permite ejecutar el flujo manualmente desde GitHub

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"

      - name: Hacer commit vacío y subirlo
        run: |
          git commit --allow-empty -m "Chore: Mantener app despierta"
          git push
